/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class image_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public short width;
        public short height;
        public short stride;
        public int pixelformat;
        public int size;
        public byte[] image;
 
        public image_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xe613eff149a08dbcL;
 
        static image_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.image_t"))
                return 0L;
 
            classes.Add("LCMTypes.image_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.width); 
 
            outs.Write(this.height); 
 
            outs.Write(this.stride); 
 
            outs.Write(this.pixelformat); 
 
            outs.Write(this.size); 
 
            for (int a = 0; a < this.size; a++) {
                outs.Write(this.image[a]); 
            }
 
        }
 
        public image_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public image_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.image_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.image_t o = new LCMTypes.image_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.width = ins.ReadInt16();
 
            this.height = ins.ReadInt16();
 
            this.stride = ins.ReadInt16();
 
            this.pixelformat = ins.ReadInt32();
 
            this.size = ins.ReadInt32();
 
            this.image = new byte[(int) size];
            for (int a = 0; a < this.size; a++) {
                this.image[a] = ins.ReadByte();
            }
 
        }
 
        public LCMTypes.image_t Copy()
        {
            LCMTypes.image_t outobj = new LCMTypes.image_t();
            outobj.utime = this.utime;
 
            outobj.width = this.width;
 
            outobj.height = this.height;
 
            outobj.stride = this.stride;
 
            outobj.pixelformat = this.pixelformat;
 
            outobj.size = this.size;
 
            outobj.image = new byte[(int) size];
            for (int a = 0; a < this.size; a++) {
                outobj.image[a] = this.image[a];
            }
 
            return outobj;
        }
    }
}

