/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class sonar_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public float range;
        public float direction;
        public float width;
 
        public sonar_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x6fdb9df15661d7b9L;
 
        static sonar_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.sonar_t"))
                return 0L;
 
            classes.Add("LCMTypes.sonar_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.range); 
 
            outs.Write(this.direction); 
 
            outs.Write(this.width); 
 
        }
 
        public sonar_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public sonar_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.sonar_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.sonar_t o = new LCMTypes.sonar_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.range = ins.ReadSingle();
 
            this.direction = ins.ReadSingle();
 
            this.width = ins.ReadSingle();
 
        }
 
        public LCMTypes.sonar_t Copy()
        {
            LCMTypes.sonar_t outobj = new LCMTypes.sonar_t();
            outobj.utime = this.utime;
 
            outobj.range = this.range;
 
            outobj.direction = this.direction;
 
            outobj.width = this.width;
 
            return outobj;
        }
    }
}

